# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @param n the parameter of Binomial distribution
#' @param a the parameter of Beta distribution
#' @param b the parameter of Beta distribution
#' @return a random sample 
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10,20,4,1) 
#' }
#' @export
NULL

gibbsC <- function(N, thin, n, a, b) {
    .Call('_StatComp21072_gibbsC', PACKAGE = 'StatComp21072', N, thin, n, a, b)
}

